#!/bin/sh
# git pull --rebase all cperl branches (import rebased changes from remote)

git checkout master
git pull --rebase origin master || exit

for b in `git branch --list --no-color|cut -c3- | egrep '^(bugfix/|feature|compiler/)'`; do
    git checkout $b && git pull --rebase -t origin $b
done
git checkout master
